prompt='%F{blue}%m%f%B.%b%F{green}%n%f%B.%b%F{yellow}%4~%f %Bλ%b '

# Only set to nvim if it is not already set
: ${EDITOR:=nvim}
export EDITOR

alias e="${EDITOR}"

alias add="git add"
alias co="git checkout"
alias commit="git commit -v"
alias rebase="git rebase"
alias reset="git reset"
alias st="git status"
alias db="git branch -l | fzf | xargs git branch -d"
alias cob="git branch -l | fzf | xargs git checkout"
alias coba="git branch -la | fzf | xargs git checkout"

alias cp='cp -i'
alias grep='grep --colour'
alias mv='mv -i'
alias open=xdg-open

alias corgi=cargo

function tn() {
	DIRNAME=$(basename `pwd` | tr -d '\n')
	tmux new -s $DIRNAME
}

